travis:
  secure:
    BINSTAR_TOKEN: hKDj4wXDgGlHhPbzNbfsKkiupZYWAzdM78foa8o+r3ifhlVM0nGPCPqwHTev07ACqMgOyJ40fA9nyWdRTCGh9Mwil+9YPWcYGgoVJ/uSgbD0EcsFJ9VFhXMCbc9IY8IOjzqdf0+MdMOlB+mZkvJQ1iG8tP+APMJepfWYah0HBz+KGIwUBsSjc9rf8YA5mVXiOFmX3X69CA9sD4lzqhT0oduVkl3Jd3RRp2xnrbtkWQfra/6aMJcm8QDOpf+AcnuxCg1F0zBBFeTUSXReMSy9wTHftXL9NawRHrxkm6KKWLDlSWzPyeghNGgOnzOgkwPHgQvXvHvi15KuKQougIuqOjiN8ZjPyJE9LFLfbJoKUe8jy+cD2r7kLIJv6jyKCLqBZe9JlqNBZ+n1gxBZ58ykBTtF69B3dN9fnUDxvr5V9BCzckyc/wV9TnrCjamS1w1Zgw+jTQxTEaVdbqnaXeZH1FQT5y7CCMyL6OtlsyKoDvpPkaDpjvQaqiccFtWoS83VvGv6l7vurjvIx/NJoWQqZUpdUoiEO02ik39TYhYYAVa10Lji/CZMmIgIQ3LClxsasu1wynkguED5rJlwpjDT7lakNr+3K0zPSi8PvdTn0GVGiN/fhJmiX+1G9hR65X/T40ILnBxJc68Mbd1TduYhNkVg5XxtEiPju0R9Rym3G8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
