travis:
  secure:
    BINSTAR_TOKEN: xlgHR3r3CjsxJ7gTj34ePnDh5IBWTuwwllFpb/N/+YhQ6WbVp5Rrh+3ghNWeg4h8VZz+AWGF6ZUDDrBJbAVCJ19cHAqO4X8sbnT12BGy8khFSAARaxPqfnZT61dfEGOw0r4YGX+FEMv5FJRES0ZO2v9j3nwwcP67tsW2x45ErJ4j0gRrR7xT84Ju7YVCCvMhORk4iSHRF5cz2GYsuuy9oyP9fxsU6OfI6W4BbL8nzddLZhcexodPNFXtxoerOqyAPao2sFYup1hQnrYfq87o9yxzp9xbReAFNXgmwo8DBlCTLTqkgvn29ySwrtRbeoL2iT8TCVlRi4jxxuXc0bKzbCAuPqrj9f1Z0NB1qqS4yo2TYc90Wd9eVLDKLZRFW+DF1vb+D9AJmn1rqRYY4NYqLeI1kvXntha0MAF3yHwFS0pvseV9jGzdISN6Ld1K+G9QPHYjwKUEQNql9YG3f4hs4MQZzCFe2AVvgZ6mesXbRbg2hYGMAKTndyLW+wrj601c57TPAIJLo4zNwIUbbcrz7UvlMPbhoOWfHyObxNfwK/ahw+RXrilAPKfJ2Cl64B3cRQaoOcR9u0TfxJXdSMuuBUmY8T9hKI2YUPspCccRC8CvTUD9TzPbWq0NMpAN8vlMCgPgxc8lK/q09cTP0GJnRntLcAhaqBwVfImSQ2k+x/0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
