travis:
  secure:
    BINSTAR_TOKEN: k5d67/qSMcoFjtF7GcxkjrURZO4rqNuFnoxuszEk6xbukou6BP9Qjh+5EocM2/NMbtrynGYu0CGZlGXQzW4yfVOAwlSEvB1ZBtTUgy6P3YG56w0tmw+k1F08kjsHAFRu4P/DgHqhV3C5iOvjM69OMQeIHdCwobo+N1KeS3f6hox3yEVyfbrmKVMaRwxvSuhQetW4T0Lf8LV3Me1vzLbHELYbANg8HKP486yE/3us+MctUOZ1hIvryRbkn0uq81nfAkuMRNuiQxYPW0cFvYR0gQnqOa9HI/tPeom6uqV1BtRx5ECg8L0Ua5at2DTaxciDWXluKSUcAw7TdAtL13gf70fh8SyJ31zfWqeWa3UepveGUe9pw8E1XkZshLF+Y5rnyvMON+vXkQ5gfGhgUzmrjt48df71kMuEVhOgKkrA5SgOyglBhZD3+fAwLwa3eqpV6xAJyuYpDCiOCrYnHql7+u36j1OzbAAxTMy34VyKWCdleQ/fqcpVb0Ef+zJjBM5J/S+vlXZ1/8QhJX7prxjNa9smP5LTe6k4F0/Rb3YhyfDxLEQ1ygthJWUKWT4DkbjkONt2Q0rpOU81iBgkXV0ML6KsM08OZMjp2ZxK55Q8h9Wkb1tJgnIqNIbWDFqAurDWWkWehJ77fR+bMYUngaNY0jr4j0FxEzLcNL93iYpolBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
