travis:
  secure:
    BINSTAR_TOKEN: VmX9ae60d51T+mmJhtHFlCq29nXTPffVQXouS3+oz/QgfRPqDoa08jBwa6pTfB0N6eQxM2QTSzfhHnY/PY0IfDqmuDqn4EDbjGugpDN66kLvsHk7QBI3ytTNXvovbIk32XiLEpnmNe1IHrb9eT+EVzIi7pjxZZSWGh2gy9CLgbsuNyJX7XsXmBbLlAK4spAFAc5kMHe8BRkJ1HsL8cuVd84othfXiP6/6Rc23jw3xF1EJifcDeMdCin6zemaW5orO2rYkfbpj5ahXnWglEkBG7MAtjZB/e8jQTmfH97T9LPl2kRfscuSdr7HwJhXcQ1aDlJPsSQhno1Gq8JNE01IO9SWrqInqs4iZxS1fRlJru7jSOuBivIVlQkmEt2WIyirKGIz5lBPHGy47IQy7vRhZHt9RzCyhFr0cYIZTAEjuLOJPNhT2RArmb2YLaLmm45PG00H9/pq/36cw6MXbgN+aORl/UeqqenBesmC5I6BTNI1FnEBCocQcLxxMpNko9LpAyU6PS/BcW/EKDkxzqegN0R7jFEQSM1w2kCneJV//C+I+6fkplaUjlmknfvpo6cOIovQcD6BCVAjWWzxbCdClROriTVpsofNgKX0frOsGU2DUbYcuFTUV16zD+vz1z1inCI/KLld7JNPY5wUMjPTTTQxk7Q3I9FXVdh2+Mvqqio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
