travis:
  secure:
    BINSTAR_TOKEN: VaTut7rs2gEfAmVYyhpJwde4YVG+x6hv66j4MM0Cql3cdAIKjBaIyDHiFwuVMJd4wgFd5cFZqRN4uX8LFOhnf1sOd9RNOsf1VYlZnZlzYnfEmWNjBjk4QaE2UhXrDxm4rj7E0dZU4ZI049xmZvQdgmNY4k5kYUjph4sXk6414FWeDnEw9EnetgZuw3D6fbaKsN53A0yL0fhuChOkq1cD6+FsZDnfVhAwOwBDRoPQamdaAThHaMM79h1u9WGZoxWodX6mpJupwgsJqPojqCI4oI1D+FakzeiY0faE6BnMuBPv/rbBbxcBArF/ig4IMUkZky/vMnpxpnbyvY2n2mIzbtL21oTLgXPUdWd/zuj5D0BLG1N/1Fsvan77kC8Bc9WPAEaVCQy7ITTpxS1FThtzrWH3vi0/3UDaVOlkwE8nCKiLQBY4tKR08OwE5f42cpIMWQSk34JvKbSNwN3DTrEwbftN2JV0ksRTE5uYpivvCsUcSJMIwFUb/xlvbhGsVXIzxv1NrmCENldo29gZgExGxDj9lezXC4aAHouO3DUbg6y16AUY2dT7PMVe4Bd8jh7LmLydoLejKP6NXaLMOyDMmhiKv/46gXMXbR3EgkET8FDBLCkZ3gmICETwjf1P+70RcQ3AlvCGViKe1e6ENPtY94U5ZhYqP6KiWyM6eLuh3yw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
