travis:
  secure:
    BINSTAR_TOKEN: KqWdnDDwkive5vN02Mzmngsn+ENcaMYF7mpJtYU/lbRMIvRLIgVp8D9ToKwzVPJAYYwj818pD2ItUui87vy0nq+l1TIuwq8ALyEWTFUmnhpDNY7kn7E4fiT3V35fBDZ4xvrjR8JmBLvrgeu41XZ+angxV1HgqVvebnGT8B2hDwPzmg56YFnynfDqnBqdk8Wh2J/UNG5kWoOdzaj/Ocf/d3+RBZqvDoyeuvWMqZYrzCm9a8ambKnhihoz2enPMraoh4pF6jCRoQ6GxJToX5GWJeEk0XDUJHNRCwBrbIuFhWqjrclJ4P+G8zuPbL+cV8ZgV0mtize3eJ1HkBhOjSFDMK84q2PH4K8DLyYI8hooX/fCpi0emAZrhroOVje9BknbxWOlplGhdSC2EJwONKrkXQaNppFDdSZnR9/SJrnWDi94vAUwq9k4nW2IUd7dcjWbT0WtvADT98k/koMCiC5LJMhtqVui12HQmPYmZPVJxdqVMtYq3Yleqq/80t2Ad0R8idY4bbj+1TfiT3RL3uqJSMarqbHV5l3zwiwaHOrtBg7CeoDJvrEh3823wHIwo2FGLDh4d2b1OahsBe6h5RY8HDix76VvG+Db/Y1Syh8qqTYLl7XmepUnJSntA1s7tBXb6bTB5Yc3yjcD59Hg2Lwg2p1dpkk4C4fxi9AuWTNUn+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
