travis:
  secure:
    BINSTAR_TOKEN: wsTxtF3Eh304WNyVaaAumJLoRoPM1DbM11ARnBiRPJIxHMusMvjgdhXQVg42C/BJfnbhRh5OaiBi4NqMdyVxUgRMcL2VX9ApgcqkgWi0izLBcc6p5aX6844jN1NW5ASDWy38sPXRmdTEXF/2vC78BDcHd4UGzPoceK8rZ/B7++QLOp9aCpzxf6/Zne3mStzNpegWDmV65U35L+APHYGfHVtB9hesrEAH16rID1moC0FCrrvSjT/VgF+AczspaQnKsYRCKZWHwYjh1Gr85l+IrJPRrrxOUix6vA9QnKgkwemKZv6UDU+k3tGe777th8hIUMhFtRuu+KYzFXW58loycrJ2PnImOC2D1ukMp13y5KOQgsOmAYwGaPoYCLICVGwUYAtGWweUvm9qPiEHW5ewI9XL2S7S37cluGzlqIWPqF8iCHPnhXTYtHB8Z9RBPExN7ObM8nH5VGQrk/Bi2qkehfXA0il1lv+DBttD6YiYUYGybr38PwQZnKr3SqXyI4YvIzpnAJe3j60RnqUabLTTAn+dJHPiIsK7izuPORyj5rjmBod/upehSE/JIZUWQYS3TUZ0/7a609hXPVTJA+FBLQP8UdRl/ODUWCl8Rx7hywrS1hCE8xfVXgN5CIiDxz1QqDMGn6hHkjAp7XkxtSQ8/OfdGzLXgrWXTqvfDGag2zw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
