travis:
  secure:
    BINSTAR_TOKEN: AcMlyOluQm6TpCjMb3+laSGXaGbpgHjcHUtPOQOeRhff6z1ct59+m0fednSbJCVxAdBiLCG8yakDmi6nl+CONyCtc11GlC8Ka8qoLWq1fiegPPvf2Sb2yw5e+VaC8r5QgrxysnPEXe31nWgZlyKfXwSt1VXYbNUNLmwl0i2xL8VcTIPM0KFvAskVZv+vuW+mpY8V7SyWYZmnvgL15hoBGAlvei2qSacn3yzEixZus4soTcSqFcMKWGcEFa4FDlzlVIma2iwWH2I2+DgIJBolHDSKfJWfUpivroGy6JIUxouJi6pHn5xrzaWUSkL4I8N97M/OnQEBl4b47H/SgFuq5WMZ6gGR29y/Bs++/t30t+VQw0ITSSL6cOD0FimsB/Tbgz0R5YmvcPY9UFwl+b1lFh43+iOEgQ8enIl6BHzvy24x0+qgyBfRzD8t+9t/DtybTTMQaOr2IGrYAZbgKcjbZ6/wzhIHRJr+wztIxw93ahu8+7QBQhJdz/2tyAoBwPwJe5PV5OWzBGcHKdWGw9SDWJLc/RUyPb1fT+cTGnAmJQVKhTUgvtsXh4PXQkfEjmnWTplxtuQzecCbO07OnqgOuu8RruSg7k0Tp0IVev4ALOK+Ba8z8Mlo4l5b4PcnhUpcOjNObW7kZaGKpQ4TikTJ/9S0wsZvNU0QSR2K8PxR3SI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
