appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OalhON2tERBYz6tOGICt1Rjb9uVihem4cSlGEZ5Hb4UAKP/LIDBC8fMRBMw0uo8N0nH2CrBnwdTJat378pCDgWR0dOmGkW2otQGe6OpybL7F6ggKZmpten9m2qAzMaN//yOa1QOoSSH6QtSEasd6Ip/FUTSQhH+IfSBy4gUWkXFBTS+1Jy5Pm5b/6pOZXJB2Kleu4ee5j3PCJ34MkPrgtiiw/f73i97FIPIB0jboSOTtlrnfRHRD8xgyRC45bNQBKGWwXed+ZHU502RFFjNmCQ0c3IBjNqqnHGsM518jbUwm1LPXb0RK5iSiNT5nnich2pWe3ehIb7lMdhm3s+WoQ1AcvO3CYFCkEhlu5qGDeBXqWbQO34q/fTwtGVVYsjCRpFIzang3S5evqColyaVU3CmpwKGGfgxtcny4++Wo/uIRF5N/BDix/YWtcyph3Bjb1KdvhXTKO5ehF2e92cGree9QR5ZotE2X7Czpgmt6uG+F9bqetcF9p6m60yiTu7OasUvf+i9vbQNE40EsmxN2WB8KrSMLAivZPbb/41FJGFKD38kfgnVSSAjpORKWBo3Tx2PWlYGQz1R1L5pZgpXSWzLRX9rwzawXm01kdWQHVV4q8FWDV+yi89e/z8I20x1QqZV2skF8iLLkLjRY174L9XhETWEFkY5DRJ1zh3wzxFE=
conda_forge_output_validation: true
