travis:
  secure:
    BINSTAR_TOKEN: D34MFLASrySmzYRun5HDosYXabzQaOT64jFCFyeFAXbitE6/qg306FE9O0y4BvWvezHHm8YUqC5LtU3UIUCmPBKXtYXNd6CQm3Mtyoon4rPUe1dgu2XLmMh9F+uKsAWaxuSK3T0St/Ff7vKcT8+7YkYRs3XLiyCB5cgxjLGsEtKmd2gys+v4F+0vhTP7wH8BpNlE5xdUAOaMBwT2ZA14nNHqFn0Fus4fFOtiKJIkoXwLJzlyIrUVZ32PI3Cvz3bj63UKqk1TVf0akkq+rq/IXVk+qhjU5FIU5HzsNEpwMN1UCRBSUsLALE0xbS98Q90KwDOi9KCpQ4i9wrkW4T/BIrwDQVVNAyCfNtAzwrBcM8R3kzR3t/Q4PvKoAJu3wXxHbCjajJe/4EHJCQm8vo05D8GQIu0uMhDdKrkC6tpQYcOpuyNXkcIzeO2NHq/IK5XBfN5H7pe5jL5CSURe/IMMJe/baUTxO1OxUptz3yIz40P+Xd5PuA6kcTi7llha9PpXnzxKgcLH/OtayyEvD/jKcPlDPb3YQsWLHENyUa/8KnpxvfSboJQ/6eL7H3SHaCbLSvz4wN1UNuDlqUHaCQNu49ktZgv7jXEpSWjHKFn2Q2xB9nhgnLjmc2oVzOjD84DMQHcL1XCHvsx0SCR/0xI54GZm8nU6pRM1624Zz2I+LXE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
