travis:
  secure:
    BINSTAR_TOKEN: toaJL9MVelwUJiXqdygrq3jCYO7YBk0NyQT15RIxKBXbdOl51fsvS1I4kf7y2C/5Gz96jbghlbw1uGdxDeZGWHxR9JDtOQPVUkt7bUu4/fS7EOfNGBBXEDDMyakTZatWnuxuxE1rNRH8brz3mRLQOJquCXyUOZjzwffYa8JZaJKsWhXFfsoVkHq0nPYf/ADIi79mJXBIjWbFde5mN2l+7Eykgo5sw+GcK+wFc00hdB+b8/o+nvQSP+vIQaCrrWrsrI5E8RIhRxj0DeG/A9G+ONj/nMJ7RmyrOvoCxBWoc3/KyY2sRgV6cNP9RSoeyRwYSL1oXNGZ/U7LFAQALBZmIWHPG3ytFSwj5HmrewHR2Nu/Iac0bL2cqFoL9mUwsuyZu+ZPt2mil5LeTG1hJWgiCaToowF51EqM+EornEt/DId/dq4c2viZJklLZ6xDgvLfWKakzybEe9JrgLym0TcXhSwcG6ygNIm+jVjbrbLzSgmSjy+L3r8Dyf2AeHEiCXh2+1WchdWXshy944DlurB4eeNcvtMrbWFiWeEmpildMjXmHcRrpYtK078yyjjF0f9VtaBmrFFJ3MRLXDyCzmDiwWEEpMYi25JDRI3Z+feKXqQtjux62XG5Bnx/0369XMJZ0wV3NctE9wQfguV1AZ/J4bhtXznCba5iYErWR8PdFR4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
